# Generated by Django 4.1.7 on 2023-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=15)),
                ('description', models.TextField(max_length=1000)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField(default=1)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('experience', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
